export const RESOURCEINFO = [
    {
        craft: "Crochet",
        name: "Where Did Crochet Come From?",
        videoUrl: "https://www.youtube.com/embed/WY40rq8ykFI",
        importance: '<div><h3>Why Is The Origin Of Crochet Important?</h3><p>While the birth place of crochet remains unclear, having only evolved to a form we recognize today in the 1800s as it gained popularity in Europe, it is still fascinating to see how cultures around the world explored similar practices. By piecing together even a rough timeline we can get a glimpse into the past and understand how such a treasured pasttime survived the ages. It is also interesting to see the transition of crochet from being a mainly practical craft to an almost entirely leisure-based one.</p></div>',
        instructions: '<div><h3>Theory #1: Saudai Arabia</h3><p>This theory suggests that crochet began in Saudai Arabia before spreading eastward to Tibet and westward to Spain and then other Mediterranean countries via trade routes.Pamir culture provides some evidence for this theory as their traditional Pamir hooks, thick and colorful socks, and overall culture are closly tied with tied with ancient Persia (a place it is theorized Arabian crochet reached due to similar evidence in the Mediterranean). Otherwise, there is little more evidence that has been popularized.<img src="/assets/pamirSocks.jpeg" width="450"></p><h3>Theory #2: South America</h3><p>Some of the earliest examples of crochet in South America come from adornments supposedly used in rghts of puberty. Primitve tribes where said to crochet these adornments using simple stitches. Sadly, there is not much else surviving information.</p><h3>Theory #3: China</h3><p>The most common theory is that crochet spawned out of the ancient Chinese practice of tambour. Tambouring did not reach Europe intil the 1700s, and even then did not take on the name crochetuntil the end of the 18th century. Tambouring consisted of stretching a background fabric tightly over a frame. A thread is held underneath the fabric and a hooked needle is pushed through thefabric, hooked on a loop of thread, and pulled back through the fabric. Chain stitches where accomplished by working the hooked needle, with the thread loop still around it, back through the fabric father down with the new thread loop pulled through the old. It is believed the thread was very fine as surviving hooks are a similar size to sewing needles. Early examples include 3D dolls that seem to me made of crocheted stitches</p><img src="/assets/tambourHook.jpg" width="300"></div>'
    },
    {
        craft: "Crochet",
        name: "All About Yarn",
        videoUrl: "https://www.youtube.com/embed/jXN3rOrr_6Q",
        importance: '<div><h3>Why Is Yarn Weight Important?</h3><p>Yarn Weight, used to describe the thickness of a yarn skein, is an important topic to understand. Many patters you will encounter give a reccomended yarn wight (and hook size) for good reason. Yarns typically come in 7 thicknesses that range from the thickness of a thread to almost the thickness of a finger; the amount needed and hook used can vary greatly. Some yarn weights are also easier to work with than others when it comes to beginners: a heavier (thicker) weight tends to be reccomended. It is also good to keep in mind that some wieghts have alternate names (e.g. weight three is also called light).</p></div>',
        instructions: '<div><h3>Telling Yarn Weight From Skein Label</h3><p>The most common, and easiest way, to determine yarn weight is to look at the yarns label. Pretty much ever yarn skeins label contains a symbol or description of the skeins wight. A yarn weight symbol is conprised of a skien of yarn with a number overlaid on top of it. See the below image.</p><img src="/assets/yarnWeights.png" width="800"><br><br><p>Each yarn weight also comes with a reccomended hook size (the symbol as a whole refered to as gague). For knitters, there is a similar gague section for knitting needles. For example, it would not make much sense to use a teeny-tiny hook on jumbo yarn. This symbol is typically located near or next to the yarn weight indicator. The symbol itself consists of a picture of a crochet hook, the hook size in milimeters and US size, and numbers along the left and top side that indicate the size of the gague square. The numbers along the right and bottom of the square indicate how many rows and stitches the gague sqaure comprises of. Gague squares are used to help crafters understand how large/small/tight/loose their sitiches should be for a pattern.See below for an example.</p><img src="/assets/gagueExample.jpg" width="500"><br><br><p>Let us break down this example. Firstly, it is reccomended to use a 6mm hook, also known as a US J-10. The gague sqaure should be 10cm by 10cm or 4in by 4in. To acheive this size, there should be 12 rows of 11 single crochets (sc is the abbreviation for single crochet).</p><br><h3>Telling Yarn Weight Without A Label</h3><p>Now having a label to tell you a yarns weight is all well and good, but what happens if the label is missing? Most crocheters and knitters then use a method called Wraps Per Inch. This method requires a ruler, the mystery yarn, and (optionally) an object with a consistent circumfrence.To calculate the weight, simply wrap the yarn around an inch of your obejct (or ruler) counting the number of wraps. It is better to wrap a little tighter since you do not want to leave gaps or loose pockets. Once you have the number of wraps, simply match it to the standard number of wraps for a yarn weight. Below is a chart from the Craft Yarn Council (CYC).</p><img src="/assets/wpiChart.png" width="500"></div>'
    },
    {
        craft: "Knitting",
        name: "All About Yarn",
        videoUrl: "https://www.youtube.com/embed/jXN3rOrr_6Q",
        importance: '<div><h3>Why Is Yarn Weight Important?</h3><p>Yarn Weight, used to describe the thickness of a yarn skein, is an important topic to understand. Many patters you will encounter give a reccomended yarn wight (and hook size) for good reason. Yarns typically come in 7 thicknesses that range from the thickness of a thread to almost the thickness of a finger; the amount needed and hook used can vary greatly. Some yarn weights are also easier to work with than others when it comes to beginners: a heavier (thicker) weight tends to be reccomended. It is also good to keep in mind that some wieghts have alternate names (e.g. weight three is also called light).</p></div>',
        instructions: '<div><h3>Telling Yarn Weight From Skein Label</h3><p>The most common, and easiest way, to determine yarn weight is to look at the yarns label. Pretty much ever yarn skeins label contains a symbol or description of the skeins wight. A yarn weight symbol is conprised of a skien of yarn with a number overlaid on top of it. See the below image.</p><img src="/assets/yarnWeights.png" width="800"><br><br><p>Each yarn weight also comes with a reccomended hook size (the symbol as a whole refered to as gague). For knitters, there is a similar gague section for knitting needles. For example, it would not make much sense to use a teeny-tiny hook on jumbo yarn. This symbol is typically located near or next to the yarn weight indicator. The symbol itself consists of a picture of a crochet hook, the hook size in milimeters and US size, and numbers along the left and top side that indicate the size of the gague square. The numbers along the right and bottom of the square indicate how many rows and stitches the gague sqaure comprises of. Gague squares are used to help crafters understand how large/small/tight/loose their sitiches should be for a pattern.See below for an example.</p><img src="/assets/gagueExample.jpg" width="500"><br><br><p>Let us break down this example. Firstly, it is reccomended to use a 6mm hook, also known as a US J-10. The gague sqaure should be 10cm by 10cm or 4in by 4in. To acheive this size, there should be 12 rows of 11 single crochets (sc is the abbreviation for single crochet).</p><br><h3>Telling Yarn Weight Without A Label</h3><p>Now having a label to tell you a yarns weight is all well and good, but what happens if the label is missing? Most crocheters and knitters then use a method called Wraps Per Inch. This method requires a ruler, the mystery yarn, and (optionally) an object with a consistent circumfrence.To calculate the weight, simply wrap the yarn around an inch of your obejct (or ruler) counting the number of wraps. It is better to wrap a little tighter since you do not want to leave gaps or loose pockets. Once you have the number of wraps, simply match it to the standard number of wraps for a yarn weight. Below is a chart from the Craft Yarn Council (CYC).</p><img src="/assets/wpiChart.png" width="500"></div>'
    },
    {
        craft: "Embroidery",
        name: "Where Did Embroidery Come From?",
        videoUrl: "https://www.youtube.com/embed/v1B9u6L5A7Y",
        importance: '<div><h3>Why Is The Origin Of Embroidery Important?</h3><p>Embroidery is one of the oldest known fiber craft forms and undoubltedly shaped the other fiber crafts we know and love today. Looking at the acient pieces and depictions that survive to this day give us an unparalleed look at what life was like in those eras. While this is true of most relics that make it to modern day, it is especially true with embroidery as its function was a tool of expression.</p></div>',
        instructions: '<div><h3>Depections</h3><p>Some of the earliest evidence of embroidery comes to us from the Acient Egyptions, Ancient Persians, and Ancient Greeks. As for the Acient Egyptions and Acient Greeks, surviving artwork depicts people dressed in embroidered garments. For Ancient Egyptions specifically, tomb paintings show clothes, cough covers, hangings, and tents that were highly decorated. Ancient Greek vased dated to be from the 7th and 6th centuries BCE depect people dressed in embroidered garments. The connection to Ancient Persia is a bit more vague, though around 490 BCE armor consisted of quilted garments.</p><h3>Surviving Work</h3><p>The Scythians are credited with having the oldest surviving embroidered pieces, dating between the 5th and 3rd centuries BCE. The Byzantium empire was well known for its lavish gold ornamented embroidery. China too has a history with embroidery: its earlist pieces being attributed to the Tang dynasty (618-907 CE) though its most popular pieces coming from the Ching dynasty (1644-1911). However, it is India where embroidery as we know it may have spawned from. Numerous examples from the Mughal period (starting 1556) survived and may have passed along to Europe via East India Trade in teh 17th and 18th centuries. Many other regions too produced surviving embroidered works including Islamic Persia, Dutch East Indies, the Middle East, and Turkey. Interestingly, forms of embroidery also developed in South America, where the natives practiced Featherwork, in North American tribes, who embroidered skins and bark with dyed porcupine quills, and western Africa, where embroidery was a common embellishment. In the beginning Northern European embroidery was mainly ecclesiastical until the Renaissance where more secular influences began to take hold. By the 17th century however, embroidery was transitioning from a professional to an amateur craft (this being proven by the switch to more decorative embroidery). 17th and 18th century North American embroidery followed this trend though with simplier designs and stitches used to save thread. By the 19th century most forms of European and North American embroidery were superseded by Berlin wollwork, a type of needlepoint. </p></div>'
    },
    {
        craft: "Knitting",
        name: "NobleKnits",
        videoUrl: "https://www.youtube.com/embed/mthSV3vQX_w?list=PLtK6f0cHnIH068Qu66KNAoWWwB8SSMp0o",
        importance: '<div><h3>Who Is NobleKnits?</h3><p>NobleKnits is a blog run my Nancy Queen, a self-proclaimed knitting and crochet expert who has been honing her craft for over 20 years. Besides writing four books on needle craft and owning two yarn stores, she has even appeared on QVC with ho-to kits. She enjoys knitting and crochet becuase they allow her to relax, create something with her own two hands, and she feels they are great ways to pass the time.</p></div>',
        instructions: '<div><p><strong>YouTube Channel: </strong><a style = "color: blue" href="https://www.youtube.com/channel/UCR1sCckkccfbnhTeD-4SqXQ">https://www.youtube.com/channel/UCR1sCckkccfbnhTeD-4SqXQ</a> <br/> <strong>Blog: </strong><a style="color:blue" href="https://blog.nobleknits.com/">https://blog.nobleknits.com/</a><br/> <strong>Facebook: </strong><a style="color:blue" href="https://www.facebook.com/NobleKnitsYarnShop">https://www.facebook.com/NobleKnitsYarnShop</a><br/> <strong>Instagram: </strong><a style="color:blue" href="https://www.instagram.com/nobleknits/">https://www.instagram.com/nobleknits/</a><br/> <strong>LinkedIn: </strong><a style="color:blue" href="https://www.linkedin.com/groups/4249636/">https://www.linkedin.com/groups/4249636/</a><br/> <strong>Pintrest: </strong><a style="color:blue" href="https://www.pinterest.com/nobleknits/">https://www.pinterest.com/nobleknits/</a></p></div>'
    },
    {
        craft: "Knitting",
        name: "What Came First, Knitting Or Crochet?",
        videoUrl: "https://www.youtube.com/embed/0-iHnzTy6Qo",
        importance: '<div><h3>Why Is Knowing Which Came First Important?</h3><p>Long story short, it is not important. Both crafts have a long and storied history, and both are fun to learn and practice. It is simply interesting to see which predates the other historically. </p></div>',
        instructions: '<div><h3>Knitting, But Second</h3><p>While it is true knitting does predate crochet, they are both late to the game compared to Nalebinding. Nalebinding is Danish of origin and can be translated to mean "binding with a needle" or "needle binding". <br/><img src="/assets/nalbinding.jpg" width="500"/><br/> Despite it being ancient in origin, it is still practiced today in Pero, Scandinavia, and The Balkans. Being its ancestor, Nalebinding can be mistaken for knitting despite knitting first appearng in Ancient Egypt. All in all, it is safe to say knitting came first (between just knitting and crochet).</p></div>'
    },
    {
        craft: "Crochet",
        name: "What Came First, Knitting Or Crochet?",
        videoUrl: "https://www.youtube.com/embed/0-iHnzTy6Qo",
        importance: '<div><h3>Why Is Knowing Which Came First Important?</h3><p>Long story short, it is not important. Both crafts have a long and storied history, and both are fun to learn and practice. It is simply interesting to see which predates the other historically. </p></div>',
        instructions: '<div><h3>Knitting, But Second</h3><p>While it is true knitting does predate crochet, they are both late to the game compared to Nalebinding. Nalebinding is Danish of origin and can be translated to mean "binding with a needle" or "needle binding". <br/><img src="/assets/nalbinding.jpg" width="500"/><br/> Despite it being ancient in origin, it is still practiced today in Pero, Scandinavia, and The Balkans. Being its ancestor, Nalebinding can be mistaken for knitting despite knitting first appearng in Ancient Egypt. All in all, it is safe to say knitting came first (between just knitting and crochet).</p></div>'
    },
    {
        craft: "Crochet",
        name: "Single, Double, Half Double, And Triple Crochet",
        videoUrl: "https://www.youtube.com/embed/mjNyr7If7UI",
        importance: '<div><h3>Why Are Single, Double, Half Double, and Triple Stitches Important?</h3><p>These four stitches are important becuase they help make up the foundation of crochet. These are the first stitches you will learn (after slip stitch) and a majority of patterns are comprised of them. Even advanced stitches incorporate these four stitches into their patterns.</p></div>',
        instructions: '<div><h3>Single Crochet Stitch</h3><p>Insert your hook into the stitch and yarn over your hook. Then, draw your hook through the chain. Yarn over your hook again, and pull though both loops on your hook.<img src="/assets/crochet-single.jpg"/></p><h3>Double Crochet Stitch</h3><p>Yarn over your hook before insertering your hook into a chain. Yarn over again and bring your hook back through the chain, you should have three loops on your hook. Yarn over again and bring your hook back through two of the loops. Finally yarn over and bring your hook through the last two loops.</p><img src="/assets/crochet-double.jpg"/><h3>Half Double Crochet Stitch</h3><p>Yarn over and bring your hook through a loop. Yarn over again and bring your hook back through the loop, you should now have three loops on you hook. Finally, yarn over again and bring your hook back through all the loops on you hook.</p><img src="/assets/crochet-half-double.png"/><h3>Triple (Treble) Crochet Stitch</h3><p>Yarn over your hook twice before inserting the hook into a chain. Yarn over again and bring your hook back through the chain, you should now have four loops on your hook. Again yarn over, and bring your hook through the first two loops on your hook. Repeat this step twice to finish the stitch.</p><img src="/assets/crochet-triple.png"/></div>'
    },
]